//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pe.com.ciberelectrik.wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_sistema
    {
        public int idlog { get; set; }
        public int codemp { get; set; }
        public string accion { get; set; }
        public string tabla_afectada { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
